### ISSUE TITLE
Unlimited Map Size?

### ISSUE THREAD

**Issue by Dofuscan** [samuelyuan/PolytopiaSaveEditor#1]
Hello, I love this code, but when i try to expand my current map size in my save file from 900 (30x30) to 9000 (300x300), nothing changed, so i wonder if there's extra command input to do to make it possible or idk
```
.\PolytopiaSaveEditor -input=meow.state.decomp -mode=expand-map -value=9000
Input filename:  meow.state.decomp
Output filename:
Mode: expand-map
2024/07/25 19:20:45 Updated value is over 256

**Comment by samuelyuan** [comment]
You would have to modify the source code to remove the restriction if you want row sizes over 256. I added this check because I don't know if Polytopia can handle large maps very well. If you're trying to create a 300x300 map, the value should be set to 300 instead of 9000 because it's based on the dimensions.
